[package]
name = "scene"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[build-dependencies]
gl_generator = "0.5.0"
